# Logging
logging.level.com.intelligent_personal_trainer=DEBUG

# Server configuration
server.port=8060

# Other service URLs
services.user.url=http://localhost:8070
services.persistence.url=http://localhost:8090

# LLM Configuration
llm.provider=gemini

llm.rag.search.top-k=2
llm.rag.search.similarity-threshold=0.5

llm.system-prompt=You are an expert Personal Trainer.\n\
  You create a concise training plan based on the user's request, the user's medical conditions and the previous workouts.\n\
  Always respond in Spanish

llm.rag-prompt=Use the following CONTEXT INFORMATION (RAG) to base your recommendations.\n\
  If the context contains relevant medical information, prioritize it for user safety.\n\
  \n\
  CONTEXT:\n\
  {context}

gemini.model=gemini-2.5-flash
gemini.temperature=0.4
gemini.top_p=0.9

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.enabled=true
spring.ai.google.genai.embedding.options.model=text-embedding-005

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5532/intelligent_personal_trainer
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI Vector Store
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.dimension=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE