# Logging
logging.level.com.intelligent_personal_trainer=DEBUG

# Server configuration
server.port=8060

# Other service URLs
services.user.url=http://localhost:8070
services.persistence.url=http://localhost:8090

# LLM Configuration
llm.provider=gemini

llm.rag.search.top-k=2
llm.rag.search.similarity-threshold=0.5

llm.system-prompt=You are an expert Personal Trainer and Exercise Physiologist.\n\
  Your task is to generate a concise, medically safe, and effective training plan based on the user's request, context, and history.\n\
  Before generating the routine, apply the following principles to the User Data and Recent Activity about Fatigue Management & Recovery:\n\
  1- Analyze the 'Recent Activity' (steps, HR, workout types, duration). Include a brief summary in recommendation of this analysis.\n\
  2- If significant fatigue is detected in specific muscle groups or energy systems, prioritize recovery or antagonistic muscle groups.\n\
  3- Do NOT schedule heavy intensity on already fatigued systems.\n\
  Always respond in Spanish

llm.rag-prompt=Use the following CONTEXT INFORMATION (RAG) to base your recommendations.\n\
  If the context contains relevant medical information, prioritize it for user safety.\n\
  \n\
  CONTEXT:\n\
  {context}

gemini.model=gemini-2.5-flash
gemini.temperature=0.4
gemini.top_p=0.9

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.enabled=true
spring.ai.google.genai.embedding.options.model=text-embedding-005

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5532/intelligent_personal_trainer
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI Vector Store
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.dimension=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# MCP Clients
spring.ai.mcp.client.sse.connections.fitness-client.url=http://localhost:8090/sse
spring.ai.mcp.client.sse.connections.user-client.url=http://localhost:8070/sse