# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5532/intelligent_personal_trainer
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging
logging.level.com.intelligent_personal_trainer=DEBUG

# Server configuration
server.port=8070

# Other service URLs
services.data-processor.url=http://localhost:8080

# Scheduler configuration
scheduler.daily-ingestion.cron=0 00 02 * * ?

# MCP
spring.ai.mcp.server.name=user-service-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=sync