# Server configuration
server.port=8050

# Logging
logging.level.com.intelligent_personal_trainer=DEBUG
logging.level.org.springframework.ai.mcp=DEBUG

# LLM Configuration (Gemini)
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.enabled=true
spring.ai.google.genai.embedding.options.model=text-embedding-005

llm.rag.search.top-k=3
llm.rag.search.similarity-threshold=0.5
llm.rag.ingestion.chunkSize=1000
llm.rag.ingestion.minChunkSizeChars=300
llm.rag.ingestion.minChunkLenghtToEmbed=5
llm.rag.ingestion.maxNumChunks=10000
llm.rag.ingestion.keepSeparator=true

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5532/intelligent_personal_trainer
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI Vector Store
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.dimension=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# MCP Server
spring.ai.mcp.server.webmvc.sse.path=/sse
