# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Set the maximum number of partitions for Kafka topics, this will limit the number of concurrent consumers that can read from the topic
kafka.configuration.maxPartitions=2

# Logging
logging.level.com.intelligent_personal_trainer=DEBUG

# Server configuration
spring.application.name=data-processor-service
eureka.instance.prefer-ip-address=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Source path configuration for data ingestion
datasource.sources-path=/app/data/sources.json